### ISSUE TITLE
Entity 'aacute' not defined

### ISSUE THREAD

**Issue by ruria** [PabloCastellano/bormeparser#26]
Hi, 
with bormeparser 0.4.0.

`./manage.py importbormetoday`

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.virtualenvs/libreborme/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/root/.virtualenvs/libreborme/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.virtualenvs/libreborme/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.virtualenvs/libreborme/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/root/libreborme/borme/management/commands/importbormetoday.py", line 32, in handle
    local_only=options['local_only'])
  File "/root/libreborme/borme/parser/importer.py", line 236, in import_borme_download
    local_only, strict=no_missing)
  File "/root/libreborme/borme/parser/importer.py", line 338, in _import_borme_download_range
    bxml = BormeXML.from_file(xml_path)
  File "/root/.virtualenvs/libreborme/lib/python3.6/site-packages/bormeparser/borme.py", line 237, in from_file
    bxml._load(path)
  File "/root/.virtualenvs/libreborme/lib/python3.6/site-packages/bormeparser/borme.py", line 202, in _load
    self.xml = etree.fromstring(content).getroottree()
  File "src/lxml/etree.pyx", line 3234, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 10
lxml.etree.XMLSyntaxError: Entity 'aacute' not defined, line 10, column 44

**Comment by ruria** [comment]
I´m sorry, wrong BORME_ROOT setting.
