### ISSUE TITLE
Problemas con la instalación

### ISSUE THREAD

**Issue by puntcat** [PabloCastellano/bormeparser#8]
Saludos,

no podemos completar la instalación en local: al intentar lanzar el ./manage.py migrate la ejecución queda interrumpida por un error en el bormeparser.regex:

(libreborme) test@tester:~/libreborme$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/test/.virtualenvs/libreborme/lib/python3.4/site-packages/django/core/management/**init**.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/test/.virtualenvs/libreborme/lib/python3.4/site-packages/django/core/management/**init**.py", line 327, in execute
    django.setup()
  File "/home/test/.virtualenvs/libreborme/lib/python3.4/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/test/.virtualenvs/libreborme/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/test/.virtualenvs/libreborme/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/test/.virtualenvs/libreborme/lib/python3.4/importlib/**init**.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/test/libreborme/borme/models.py", line 9, in <module>
    from bormeparser.regex import SOCIEDADES as SOCIEDADES_DICT
ImportError: cannot import name 'SOCIEDADES'

Hemos bajado el bormeparser en paralelo y ejecutado los tests de prueba, todos con buenos resultados. Como no somos usuarios habitados con Python, también hemos probado de lanzar la instrucción que falla directamente con el intérprete del lenguaje y parece que también falla:

(libreborme) test@tester:~/libreborme$ python
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > import bormeparser.regex
> > > from bormeparser.regex import SOCIEDADES as SOCIEDADES_DICT
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: cannot import name 'SOCIEDADES'
> > > from bormeparser.regex import sociedades as SOCIEDADES_DICT
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: cannot import name 'sociedades'

Suponemos que se trata de una tontería, pero no tenemos claro de qué se trata. Alguna idea?

Gracias!

**Comment by PabloCastellano** [comment]
Qué versión de bormeparser estás usando?
Seguramente es debido a los últimos cambios en la librería. Prueba usando la versión de la rama master

**Comment by PabloCastellano** [comment]
@puntcat Lo conseguiste solucionar?

**Comment by PabloCastellano** [comment]
Cierro el caso por inactividad. No dudes en reabrirlo si quieres aportar más información.
